import { makeStyles } from '@material-ui/core/styles';

const useBossTimerStyles = makeStyles((theme) => ({
  appBar: {
    background: '#ffffff',
    borderBottom: '1px solid #dce5e1',
    boxShadow: 'none',
    color: theme.palette.text.primary,
  },
  toolbar: {
    gap: theme.spacing(2),
    minHeight: 68,
    justifyContent: 'space-between',
    [theme.breakpoints.down('sm')]: {
      alignItems: 'flex-start',
      flexDirection: 'column',
      paddingBottom: theme.spacing(1.5),
      paddingTop: theme.spacing(1.5),
    },
  },
  headerActions: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: theme.spacing(1.5),
  },
  titleGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: theme.spacing(1.25),
  },
  iconTile: {
    alignItems: 'center',
    background: '#172321',
    borderRadius: 8,
    color: '#ffffff',
    display: 'flex',
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  brandImage: {
    borderRadius: 8,
    height: 42,
    objectFit: 'cover',
    width: 42,
  },
  main: {
    paddingBottom: theme.spacing(6),
    paddingTop: theme.spacing(4),
  },
  panel: {
    border: '1px solid #dce5e1',
    borderRadius: 8,
    boxShadow: '0 8px 24px rgba(23, 35, 33, 0.06)',
  },
  statCard: {
    border: '1px solid #dce5e1',
    borderRadius: 8,
    boxShadow: 'none',
    height: '100%',
  },
  statLabel: {
    color: theme.palette.text.secondary,
    fontSize: 13,
    fontWeight: 700,
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  controls: {
    padding: theme.spacing(2),
  },
  nativeLabel: {
    color: theme.palette.text.secondary,
    display: 'block',
    fontSize: 12,
    fontWeight: 700,
    marginBottom: 4,
  },
  nativeSelect: {
    background: '#ffffff',
    border: '1px solid #c7d4cf',
    borderRadius: 8,
    color: theme.palette.text.primary,
    font: 'inherit',
    height: 40,
    padding: '0 12px',
    width: '100%',
  },
  nativeInputWrap: {
    position: 'relative',
  },
  nativeInput: {
    background: '#ffffff',
    border: '1px solid #c7d4cf',
    borderRadius: 8,
    color: theme.palette.text.primary,
    font: 'inherit',
    height: 40,
    padding: '0 48px 0 12px',
    width: '100%',
  },
  inputSuffix: {
    color: theme.palette.text.secondary,
    fontSize: 13,
    position: 'absolute',
    right: 12,
    top: 11,
  },
  pill: {
    alignItems: 'center',
    background: '#11615f',
    borderRadius: 8,
    color: '#ffffff',
    display: 'inline-flex',
    fontSize: 13,
    fontWeight: 700,
    minHeight: 32,
    padding: '6px 12px',
    whiteSpace: 'nowrap',
  },
  neutralPill: {
    background: '#e4ebe7',
    color: theme.palette.text.primary,
  },
  dangerPill: {
    background: '#b5344a',
    color: '#ffffff',
  },
  resetButton: {
    background: '#ffffff',
    border: '1px solid #11615f',
    borderRadius: 8,
    color: '#11615f',
    cursor: 'pointer',
    font: 'inherit',
    fontWeight: 700,
    minHeight: 36,
    padding: '6px 14px',
  },
  trackToggle: {
    accentColor: '#11615f',
    height: 18,
    width: 18,
  },
  inlineIcon: {
    alignItems: 'center',
    color: theme.palette.primary.main,
    display: 'inline-flex',
  },
  table: {
    minWidth: 980,
  },
  bossName: {
    fontWeight: 700,
  },
  muted: {
    color: theme.palette.text.secondary,
  },
  spawnSoon: {
    backgroundColor: '#f7e8ea',
  },
  spawning: {
    backgroundColor: '#e3f1ec',
  },
  emptyState: {
    padding: theme.spacing(4),
    textAlign: 'center',
  },
  footer: {
    alignItems: 'center',
    background: 'rgba(255, 255, 255, 0.9)',
    border: '1px solid rgba(23, 35, 33, 0.12)',
    borderRadius: 8,
    display: 'flex',
    justifyContent: 'center',
    marginTop: 0,
    padding: theme.spacing(1.75, 2),
  },
  footerCredit: {
    color: '#172321',
    fontSize: 13,
    fontWeight: 700,
    letterSpacing: 0,
  },
  landingPage: {
    background: '#f4f7f5',
    color: '#ffffff',
    minHeight: '100vh',
  },
  landingContainer: {
    paddingLeft: '0 !important',
    paddingRight: '0 !important',
  },
  landingTopBar: {
    alignItems: 'center',
    background: '#ffffff',
    color: theme.palette.text.primary,
    display: 'flex',
    justifyContent: 'space-between',
    minHeight: 68,
    padding: theme.spacing(0, 8),
    [theme.breakpoints.down('sm')]: {
      padding: theme.spacing(0, 2),
    },
  },
  navLink: {
    border: '1px solid #11615f',
    borderRadius: 8,
    color: '#11615f',
    fontWeight: 700,
    padding: '8px 14px',
    textDecoration: 'none',
  },
  navbar: {
    alignItems: 'center',
    display: 'flex',
    flexWrap: 'wrap',
    gap: theme.spacing(1),
  },
  navbarLink: {
    borderRadius: 8,
    color: '#172321',
    fontSize: 14,
    fontWeight: 700,
    padding: '8px 10px',
    textDecoration: 'none',
  },
  navbarLinkActive: {
    background: '#e4ebe7',
    color: '#11615f',
  },
  landingHeroImage: {
    alignItems: 'flex-end',
    backgroundPosition: 'center',
    backgroundSize: 'cover',
    display: 'flex',
    minHeight: 'calc(100vh - 140px)',
    padding: theme.spacing(6, 8, 7),
    [theme.breakpoints.down('sm')]: {
      minHeight: 'calc(100vh - 140px)',
      padding: theme.spacing(5, 2),
    },
  },
  landingCopy: {
    maxWidth: 620,
  },
  landingTitle: {
    color: '#ffffff',
    fontWeight: 800,
    letterSpacing: 0,
    lineHeight: 1.12,
    marginBottom: theme.spacing(2),
    textTransform: 'uppercase',
    [theme.breakpoints.down('xs')]: {
      fontSize: 34,
    },
  },
  landingText: {
    color: '#ffffff',
    fontSize: 15,
    lineHeight: 1.7,
    marginBottom: theme.spacing(3),
    maxWidth: 520,
  },
  primaryLinkButton: {
    background: '#ffffff',
    border: '1px solid #ffffff',
    borderRadius: 8,
    color: '#d85b00',
    display: 'inline-flex',
    fontWeight: 700,
    padding: '12px 28px',
    textDecoration: 'none',
  },
  materialsHeader: {
    marginBottom: theme.spacing(3),
  },
  materialsGrid: {
    display: 'grid',
    gap: theme.spacing(3),
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    [theme.breakpoints.down('sm')]: {
      gridTemplateColumns: '1fr',
    },
  },
  materialImagePanel: {
    background: '#ffffff',
    border: '1px solid #dce5e1',
    borderRadius: 8,
    boxShadow: '0 8px 24px rgba(23, 35, 33, 0.06)',
    overflow: 'hidden',
  },
  materialImageTitle: {
    borderBottom: '1px solid #dce5e1',
    padding: theme.spacing(1.5, 2),
  },
  materialImageButton: {
    background: 'transparent',
    border: 0,
    cursor: 'zoom-in',
    display: 'block',
    padding: 0,
    width: '100%',
  },
  materialImage: {
    display: 'block',
    height: 'auto',
    width: '100%',
  },
  materialCredit: {
    alignItems: 'center',
    background: '#ffffff',
    border: '1px solid #dce5e1',
    borderRadius: 8,
    color: theme.palette.text.secondary,
    display: 'flex',
    justifyContent: 'center',
    marginTop: theme.spacing(3),
    padding: theme.spacing(1.5, 2),
  },
  imageViewer: {
    alignItems: 'center',
    display: 'flex',
    inset: 0,
    justifyContent: 'center',
    padding: theme.spacing(3),
    position: 'fixed',
    zIndex: 1400,
  },
  imageViewerBackdrop: {
    background: 'rgba(7, 12, 11, 0.78)',
    border: 0,
    cursor: 'zoom-out',
    inset: 0,
    padding: 0,
    position: 'absolute',
  },
  imageViewerContent: {
    background: '#ffffff',
    borderRadius: 8,
    boxShadow: '0 24px 80px rgba(0, 0, 0, 0.35)',
    maxHeight: '92vh',
    maxWidth: 'min(1100px, 96vw)',
    overflow: 'auto',
    position: 'relative',
    width: '100%',
    zIndex: 1,
  },
  imageViewerHeader: {
    alignItems: 'center',
    borderBottom: '1px solid #dce5e1',
    display: 'flex',
    justifyContent: 'space-between',
    padding: theme.spacing(1.5, 2),
  },
  imageViewerClose: {
    background: '#11615f',
    border: '1px solid #11615f',
    borderRadius: 8,
    color: '#ffffff',
    cursor: 'pointer',
    font: 'inherit',
    fontWeight: 700,
    padding: '8px 12px',
  },
  imageViewerImage: {
    display: 'block',
    height: 'auto',
    margin: '0 auto',
    maxWidth: '100%',
  },
  imageViewerCredit: {
    borderTop: '1px solid #dce5e1',
    color: theme.palette.text.secondary,
    padding: theme.spacing(1.5, 2),
    textAlign: 'center',
  },
}));

export default useBossTimerStyles;
